# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Juno.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 600)
        MainWindow.showMaximized()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/juneng.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 761, 531))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.modelOptionComboBox = QtWidgets.QComboBox(self.widget)
        self.modelOptionComboBox.setObjectName("modelOptionComboBox")
        self.modelOptionComboBox.addItem("")
        self.modelOptionComboBox.addItem("")
        self.modelOptionComboBox.addItem("")
        self.horizontalLayout.addWidget(self.modelOptionComboBox)
        spacerItem = QtWidgets.QSpacerItem(588, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.configTab = QtWidgets.QWidget()
        self.configTab.setObjectName("configTab")
        self.widget1 = QtWidgets.QWidget(self.configTab)
        self.widget1.setGeometry(QtCore.QRect(20, 20, 721, 431))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.optLabel = QtWidgets.QLabel(self.widget1)
        self.optLabel.setObjectName("optLabel")
        self.verticalLayout.addWidget(self.optLabel)
        self.optTableWidget = QtWidgets.QTableWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optTableWidget.sizePolicy().hasHeightForWidth())
        self.optTableWidget.setSizePolicy(sizePolicy)
        self.optTableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.optTableWidget.setAutoScroll(True)
        self.optTableWidget.setShowGrid(True)
        self.optTableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.optTableWidget.setWordWrap(True)
        self.optTableWidget.setCornerButtonEnabled(True)
        self.optTableWidget.setObjectName("optTableWidget")
        self.optTableWidget.setColumnCount(3)
        self.optTableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.optTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.optTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.optTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.optTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.optTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.optTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.optTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.optTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.optTableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.optTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.optTableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.optTableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.optTableWidget.setItem(2, 0, item)
        self.optTableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.optTableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.optTableWidget.horizontalHeader().setHighlightSections(True)
        self.optTableWidget.verticalHeader().setVisible(False)
        self.optTableWidget.verticalHeader().setDefaultSectionSize(24)
        self.verticalLayout.addWidget(self.optTableWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.depLabel = QtWidgets.QLabel(self.widget1)
        self.depLabel.setObjectName("depLabel")
        self.verticalLayout_2.addWidget(self.depLabel)
        self.treeWidget = QtWidgets.QTreeWidget(self.widget1)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.configTab, "")
        self.trainingTab = QtWidgets.QWidget()
        self.trainingTab.setObjectName("trainingTab")
        self.tabWidget.addTab(self.trainingTab, "")
        self.appTab = QtWidgets.QWidget()
        self.appTab.setObjectName("appTab")
        self.tabWidget.addTab(self.appTab, "")
        self.dataTab = QtWidgets.QWidget()
        self.dataTab.setObjectName("dataTab")
        self.tabWidget.addTab(self.dataTab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 28))
        self.menubar.setObjectName("menubar")
        self.configMenu = QtWidgets.QMenu(self.menubar)
        self.configMenu.setObjectName("configMenu")
        self.aboutMenu = QtWidgets.QMenu(self.menubar)
        self.aboutMenu.setObjectName("aboutMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.configMenu.addAction(self.action)
        self.configMenu.addAction(self.action_2)
        self.aboutMenu.addAction(self.action_3)
        self.aboutMenu.addAction(self.action_4)
        self.menubar.addAction(self.configMenu.menuAction())
        self.menubar.addAction(self.aboutMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Juno"))
        self.modelOptionComboBox.setCurrentText(_translate("MainWindow", "请选择模型"))
        self.modelOptionComboBox.setItemText(0, _translate("MainWindow", "请选择模型"))
        self.modelOptionComboBox.setItemText(1, _translate("MainWindow", "工艺1"))
        self.modelOptionComboBox.setItemText(2, _translate("MainWindow", "工艺2"))
        self.optLabel.setText(_translate("MainWindow", "最优运行条件"))
        item = self.optTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.optTableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.optTableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.optTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "进水指标"))
        item = self.optTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "最低值"))
        item = self.optTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "最高值"))
        __sortingEnabled = self.optTableWidget.isSortingEnabled()
        self.optTableWidget.setSortingEnabled(False)
        item = self.optTableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "pH"))
        item = self.optTableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "5"))
        item = self.optTableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "8"))
        item = self.optTableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "COD"))
        item = self.optTableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "500"))
        item = self.optTableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "5000"))
        item = self.optTableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "TDS-600C ABCDE"))
        self.optTableWidget.setSortingEnabled(__sortingEnabled)
        self.depLabel.setText(_translate("MainWindow", "指标相互依赖关系"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "出水指标"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "依赖进水指标"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "COD"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "COD"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "TN"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "pH"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "TN"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "TN"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "COD"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "pH"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "pH"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "N-NO3"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "N-NO3"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "COD"))
        self.treeWidget.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "TN"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configTab), _translate("MainWindow", "模型定义配置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.trainingTab), _translate("MainWindow", "专家建模"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.appTab), _translate("MainWindow", "出水预测"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataTab), _translate("MainWindow", "历史数据"))
        self.configMenu.setTitle(_translate("MainWindow", "设置"))
        self.aboutMenu.setTitle(_translate("MainWindow", "关于"))
        self.action.setText(_translate("MainWindow", "工艺集"))
        self.action_2.setText(_translate("MainWindow", "指标集"))
        self.action_3.setText(_translate("MainWindow", "软件简介"))
        self.action_4.setText(_translate("MainWindow", "帮助"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

